// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountParams = {
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * In managed auth mode this triggers the normal refresh-token flow. In
 * external auth mode this flag is ignored. Clients should refresh tokens
 * themselves and call `account/login/start` with `chatgptAuthTokens`.
 */
refreshToken: boolean,
/**
 * When `true`, reloads the auth storage snapshot before reading the current
 * account details.
 *
 * This is intended for clients that update persistent auth outside the
 * app-server process. Externally managed account pools should prefer
 * `account/login/start` with `chatgptAuthTokens` for normal account
 * switches.
 */
reloadAuth?: boolean, };
